import { DoubleCard, LargeCard, WideCard } from "components/cards"
import { Cta } from "components/global"
import { MenuComponent } from "components/shared"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { menuData } from "data/menuData"
import { Category, Hero } from "components/home"

const Home: NextPage = () => {
  const {menu} = menuData
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero />

      <Category data={menu} />
      <LargeCard />
      <WideCard />
      <DoubleCard />
      <Cta />
    </div>
  )
}

export default Home
